name: Docker Build and Publish

on:
  push:
    tags:
      - "v*"  # Trigger only on version tags

env:
  DOCKER_HUB_USERNAME: ${{ vars.DOCKER_HUB_USERNAME || 'buger' }}
  PROBE_IMAGE_NAME: probe
  PROBE_CHAT_IMAGE_NAME: probe-chat

jobs:
  docker-build-probe:
    name: Build Probe Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.PROBE_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            VCS_REF=${{ github.sha }}
            VERSION=${{ steps.meta.outputs.version }}

  docker-build-probe-chat:
    name: Build Probe Chat Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.PROBE_CHAT_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./examples/chat
          file: ./examples/chat/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            VCS_REF=${{ github.sha }}
            VERSION=${{ steps.meta.outputs.version }}

  update-docker-hub-description:
    name: Update Docker Hub Description
    needs: [docker-build-probe, docker-build-probe-chat]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Probe Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.PROBE_IMAGE_NAME }}
          readme-filepath: ./DOCKER-README.md
          short-description: "Probe - AI-friendly code search tool built in Rust"

      - name: Create Probe Chat README
        run: |
          cat > PROBE-CHAT-README.md << 'EOF'
          # Probe Chat - AI-powered Chat Interface for Probe

          Probe Chat provides an interactive AI-powered interface for the Probe code search tool.

          ## Quick Start

          ### CLI Mode
          ```bash
          docker run --rm -e ANTHROPIC_API_KEY=your_key buger/probe-chat
          ```

          ### Web Mode
          ```bash
          docker run --rm -e ANTHROPIC_API_KEY=your_key -p 3000:3000 buger/probe-chat --web
          ```

          ## Environment Variables
          - `ANTHROPIC_API_KEY` or `OPENAI_API_KEY`: Required for LLM features
          - `ALLOWED_FOLDERS`: Optional, restricts searchable folders

          For full documentation, visit: https://github.com/buger/probe
          EOF

      - name: Update Probe Chat Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.PROBE_CHAT_IMAGE_NAME }}
          readme-filepath: ./PROBE-CHAT-README.md
          short-description: "Probe Chat - AI-powered interface for code search and analysis"