name: Probe Engineer handler

on:
  issue_comment:
    types: [created]          

# Define permissions needed for the workflow
permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:
  trigger_probe_implement:
    uses: buger/probe/.github/workflows/probe.yml@main
    with:
      command_prefix: "/engineer" # Or '/ai', '/ask', etc.
      # Enable reviewdog suggestions instead of direct commits for better code review workflow
      # Suggestions allow reviewers to see proposed changes before they're applied
      allow_edit: true
      prompt: ./.prompts/engineer.md
      update_existing_comment: false
      update_comment_marker: "<!-- probe-bot -->"
      enable_tracing: true
      # Use Claude Code as the primary implementation backend
      # Claude Code provides advanced AI coding capabilities with better context understanding
      # Note: aider is the default if not specified
      implement_tool_backend: "claude-code"
      # Fallback to aider if Claude Code is unavailable
      implement_tool_fallbacks: "aider"
      # Use Claude Opus 4 for best code generation quality
      # This is the most capable model for complex engineering tasks
      claude_code_model: "claude-opus-4-20250514"
      # Set temperature to 0.2 for more consistent and focused code generation
      claude_code_temperature: "0.2"
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      ANTHROPIC_API_URL: ${{ secrets.ANTHROPIC_API_URL }}
      APP_ID: ${{ secrets.PROBE_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.PROBE_APP_PRIVATE_KEY }}
      MAX_TOOL_ITERATIONS: "60"
